# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Hugo dependencies
    before: brew install hugo
    init: echo "Your version of Hugo is `hugo version`"
    command: hugo server -D -F --baseUrl $(gp url 1337) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0 --port=1337
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1337
    onOpen: open-preview