baseURL = 'https://dylanmaassen.nl/'
languageCode = 'en-us'
title = "Dylan's Site"
theme = 'dylanmaassen'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableKinds = ["RSS"]

[languages]
    [languages.en]
    [languages.nl]

[params]
    #fontawesomekit = "e042207efc"


[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

