baseURL = 'https://dylanmaassen.nl/'
languageCode = 'en-us'
title = "Dylan's Site"
theme = 'dylanmaassen'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
    [languages.en]
    [languages.nl]
